### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by dertuxmalwieder** [menees/RpnCalc#1]
Hi, menees, and thank you for this well-thought application. :-)

I wonder about the correct license: While the `LICENSE` file says it's MIT, the "About" screen says it's charity ware. Which of those applies?

**Comment by menees** [comment]
Both apply. The license file is the [legal instrument governing the use or redistribution of software](https://en.wikipedia.org/wiki/Software_license). The MIT license is a permissive license that grants use rights, and it can be used for free, commercial, or charityware software.

The MIT license includes the right to "sell copies of the software". Think of charityware as selling the software for some charity (that I can't track and will never know about). So the *request* on the About box is that if you're going to use the software I provide, then I *ask* that you donate to the charity of your choice. Legally, you have the right not to do that. However, exercising that right would seem weaselly to me. :-)

**Comment by dertuxmalwieder** [comment]
From the MIT License itself:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Wouldn't that require license headers in the files ("substantial portions")?

Anyway, thank you for clarification. The About box does not really say it's a *request*, it reads more like "this application requires you to donate to a charity". Maybe you could rephrase it, as in "RpnCalc is dual-licensed as MIT and CharityWare"? Just a suggestion. :-)

**Comment by menees** [comment]
I'm happy with it as is.
